/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bootstrap */
        get: operations["bootstrap_v1_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Protocol Document */
        get: operations["protocol_document_v1_protocol_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /** Rename Session */
        patch: operations["rename_session_v1_sessions__session_id__patch"];
        trace?: never;
    };
    "/v1/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Session */
        get: operations["export_session_v1_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Id */
            id?: string;
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /** Created At */
            created_at?: string;
        };
        /** AgentRun */
        AgentRun: {
            /** Id */
            id?: string;
            /**
             * Agent
             * @enum {string}
             */
            agent: "speaker" | "worker" | "coordinator" | "notes" | "naming";
            /** Summary */
            summary: string;
            /**
             * Status
             * @default running
             * @enum {string}
             */
            status: "running" | "done" | "failed";
            /** Error */
            error?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Started At */
            started_at?: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** BackendHello */
        BackendHello: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "backend.hello";
            /** Project Id */
            project_id: string;
            /** Protocol Version */
            protocol_version: number;
        };
        /** BoardCurate */
        BoardCurate: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "board.curate";
        };
        /** BootstrapResponse */
        BootstrapResponse: {
            /** Project Id */
            project_id: string;
            /** Protocol Version */
            protocol_version: number;
            /** Active Model */
            active_model: string;
            /** Models */
            models: string[];
            state: components["schemas"]["MeetingState"];
            /** Sessions */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /** CaptureChanged */
        CaptureChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "capture.changed";
            /**
             * Source
             * @enum {string}
             */
            source: "microphone" | "system";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "denied" | "ended" | "unavailable";
        };
        /** Card */
        Card: {
            /** Id */
            id?: string;
            /**
             * Kind
             * @default finding
             * @enum {string}
             */
            kind: "idea" | "question" | "decision" | "suggestion" | "finding";
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Source Ids */
            source_ids?: string[];
            /** Updated At */
            updated_at?: string;
        };
        /** ClientHello */
        ClientHello: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "client.hello";
            /** Protocol Version */
            protocol_version: number;
            /** Client Id */
            client_id: string;
            /** Capabilities */
            capabilities?: {
                [key: string]: boolean;
            };
        };
        /** Decision */
        Decision: {
            /**
             * Route
             * @enum {string}
             */
            route: "ignore" | "capture" | "investigate" | "respond" | "act" | "control";
            /**
             * Addressed Probability
             * @default 0
             */
            addressed_probability: number;
            /**
             * Salience
             * @default 0
             */
            salience: number;
            /**
             * Speech Value
             * @default 0
             */
            speech_value: number;
            /**
             * Timing
             * @default silent
             * @enum {string}
             */
            timing: "silent" | "next_gap" | "later";
            /**
             * Rationale
             * @default
             */
            rationale: string;
        };
        /** DecisionRecord */
        DecisionRecord: {
            /** Id */
            id?: string;
            /** Utterance Id */
            utterance_id: string;
            /** Context */
            context: {
                [key: string]: unknown;
            };
            result: components["schemas"]["Decision"];
            /** Decided At */
            decided_at?: string;
        };
        /** FloorChanged */
        FloorChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "floor.changed";
            /** Busy */
            busy: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "standby" | "degraded" | "down" | "unconfigured";
            /**
             * Detail
             * @default
             */
            detail: string;
        };
        /** MeetingState */
        MeetingState: {
            /** Project Id */
            project_id: string;
            /** Protocol Version */
            protocol_version: number;
            /** @default booting */
            process_status: components["schemas"]["ProcessStatus"];
            /** @default idle */
            session_status: components["schemas"]["SessionStatus"];
            /** Session Id */
            session_id?: string | null;
            /**
             * Title
             * @default Nouvelle session
             */
            title: string;
            /**
             * Assistant Name
             * @default Assistant
             */
            assistant_name: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "fr" | "es" | "de" | "pt";
            /**
             * Voice Mode
             * @default active
             * @enum {string}
             */
            voice_mode: "active" | "muted";
            /**
             * Capture Mode
             * @default mixed
             * @enum {string}
             */
            capture_mode: "microphone" | "system" | "mixed";
            /**
             * Output Mode
             * @default local_only
             * @enum {string}
             */
            output_mode: "local_only" | "room_speaker" | "meeting_injected";
            /**
             * Floor Busy
             * @default false
             */
            floor_busy: boolean;
            /**
             * Partial
             * @default
             */
            partial: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /**
             * Notes Version
             * @default 0
             */
            notes_version: number;
            /**
             * Notes Cursor
             * @default 0
             */
            notes_cursor: number;
            /**
             * Title Version
             * @default 0
             */
            title_version: number;
            /**
             * Title Cursor
             * @default 0
             */
            title_cursor: number;
            /**
             * Working
             * @default
             */
            working: string;
            /**
             * Transcript
             * @default []
             */
            transcript: components["schemas"]["Utterance"][];
            /**
             * Cards
             * @default []
             */
            cards: components["schemas"]["Card"][];
            /**
             * Tasks
             * @default []
             */
            tasks: components["schemas"]["Task"][];
            /**
             * Speeches
             * @default []
             */
            speeches: components["schemas"]["Speech"][];
            /**
             * Activities
             * @default []
             */
            activities: components["schemas"]["Activity"][];
            /**
             * Agent Runs
             * @default []
             */
            agent_runs: components["schemas"]["AgentRun"][];
            /**
             * Decisions
             * @default []
             */
            decisions: components["schemas"]["DecisionRecord"][];
            /**
             * Health
             * @default {}
             */
            health: {
                [key: string]: components["schemas"]["Health"];
            };
            pipeline?: components["schemas"]["PipelineMetrics"];
            /** Created At */
            created_at?: string;
            /** Updated At */
            updated_at?: string;
        };
        /** PipelineMetrics */
        PipelineMetrics: {
            /**
             * Audio Frames
             * @default 0
             */
            audio_frames: number;
            /**
             * Audio Bytes
             * @default 0
             */
            audio_bytes: number;
            /** Last Audio At */
            last_audio_at?: string | null;
            /**
             * Stt Messages
             * @default 0
             */
            stt_messages: number;
            /**
             * Stt Fragments
             * @default 0
             */
            stt_fragments: number;
            /**
             * Stt Turns
             * @default 0
             */
            stt_turns: number;
            /**
             * Stt Last Event
             * @default
             */
            stt_last_event: string;
            /**
             * Stt Last Fragment
             * @default
             */
            stt_last_fragment: string;
            /**
             * Stt Inactivity Probability
             * @default 0
             */
            stt_inactivity_probability: number;
            /**
             * Decisions
             * @default 0
             */
            decisions: number;
            /**
             * Agent Runs
             * @default 0
             */
            agent_runs: number;
            /**
             * Note Updates
             * @default 0
             */
            note_updates: number;
        };
        /** PlaybackChanged */
        PlaybackChanged: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "playback.finished" | "playback.interrupted" | "playback.started";
            /** Speech Id */
            speech_id: string;
        };
        /** PresenceCue */
        PresenceCue: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "presence.cue";
            /**
             * Cue
             * @enum {string}
             */
            cue: "thinking" | "progress";
            /** Label */
            label: string;
            audio?: components["schemas"]["SpeechAudio"] | null;
        };
        /**
         * ProcessStatus
         * @enum {string}
         */
        ProcessStatus: "booting" | "ready" | "shutting_down" | "stopped" | "failed";
        /** ProtocolDocument */
        ProtocolDocument: {
            /** Client */
            client: components["schemas"]["ClientHello"] | components["schemas"]["BoardCurate"] | components["schemas"]["SessionStart"] | components["schemas"]["SessionOpen"] | components["schemas"]["SessionLanguage"] | components["schemas"]["VoiceModeCommand"] | components["schemas"]["SessionCommand"] | components["schemas"]["FloorChanged"] | components["schemas"]["CaptureChanged"] | components["schemas"]["TranscriptInject"] | components["schemas"]["PlaybackChanged"];
            /** Server */
            server: components["schemas"]["BackendHello"] | components["schemas"]["StateSnapshot"] | components["schemas"]["TranscriptPartial"] | components["schemas"]["SpeechAuthorized"] | components["schemas"]["SpeechStop"] | components["schemas"]["PresenceCue"] | components["schemas"]["ProtocolError"];
        };
        /** ProtocolError */
        ProtocolError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "protocol.error";
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** SessionCommand */
        SessionCommand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.command";
            /**
             * Command
             * @enum {string}
             */
            command: "pause" | "resume" | "stop";
        };
        /** SessionLanguage */
        SessionLanguage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.language";
            /**
             * Language
             * @enum {string}
             */
            language: "en" | "fr" | "es" | "de" | "pt";
        };
        /** SessionOpen */
        SessionOpen: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.open";
            /** Session Id */
            session_id: string;
        };
        /** SessionRenameRequest */
        SessionRenameRequest: {
            /** Title */
            title: string;
        };
        /** SessionStart */
        SessionStart: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "session.start";
            /**
             * Assistant Name
             * @default Assistant
             */
            assistant_name: string;
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "fr" | "es" | "de" | "pt";
            /**
             * Capture Mode
             * @default mixed
             * @enum {string}
             */
            capture_mode: "microphone" | "system" | "mixed";
            /**
             * Output Mode
             * @default local_only
             * @enum {string}
             */
            output_mode: "local_only" | "room_speaker" | "meeting_injected";
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "idle" | "starting" | "listening" | "paused" | "finalizing" | "closed" | "failed";
        /** SessionSummary */
        SessionSummary: {
            /** Session Id */
            session_id: string;
            /** Title */
            title: string;
            status: components["schemas"]["SessionStatus"];
            /**
             * Preview
             * @default
             */
            preview: string;
            /**
             * Utterance Count
             * @default 0
             */
            utterance_count: number;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** Speech */
        Speech: {
            /** Id */
            id?: string;
            /** Text */
            text: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "direct_address" | "requested_result" | "critical_finding";
            /**
             * Status
             * @default proposed
             * @enum {string}
             */
            status: "proposed" | "waiting_gap" | "authorized" | "playing" | "finished" | "interrupted" | "suppressed" | "expired";
            /** Source Ids */
            source_ids?: string[];
            /** Created At */
            created_at?: string;
        };
        /** SpeechAudio */
        SpeechAudio: {
            /** Data Base64 */
            data_base64: string;
            /** Format */
            format: string;
            /** Sample Rate */
            sample_rate: number;
        };
        /** SpeechAuthorized */
        SpeechAuthorized: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "speech.authorized";
            /** Speech Id */
            speech_id: string;
            /** Text */
            text: string;
            /** Reason */
            reason: string;
            audio?: components["schemas"]["SpeechAudio"] | null;
        };
        /** SpeechStop */
        SpeechStop: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "speech.stop";
            /** Speech Id */
            speech_id: string;
            /** Reason */
            reason: string;
        };
        /** StateSnapshot */
        StateSnapshot: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "state.snapshot";
            state: components["schemas"]["MeetingState"];
            /** Sessions */
            sessions: components["schemas"]["SessionSummary"][];
        };
        /** Task */
        Task: {
            /** Id */
            id?: string;
            /** Tool */
            tool: string;
            /** Summary */
            summary: string;
            /**
             * Status
             * @default queued
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed" | "canceled" | "stale";
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
            /** Created At */
            created_at?: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** TranscriptInject */
        TranscriptInject: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transcript.inject";
            /** Text */
            text: string;
        };
        /** TranscriptPartial */
        TranscriptPartial: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "transcript.partial";
            /** Text */
            text: string;
        };
        /** Utterance */
        Utterance: {
            /** Id */
            id?: string;
            /** Text */
            text: string;
            /**
             * Source
             * @default audio
             */
            source: string;
            /**
             * Speaker
             * @default unknown
             */
            speaker: string;
            /**
             * Language
             * @default auto
             */
            language: string;
            /** Confidence */
            confidence?: number | null;
            /** Committed At */
            committed_at?: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceModeCommand */
        VoiceModeCommand: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "voice.mode";
            /**
             * Mode
             * @enum {string}
             */
            mode: "active" | "muted";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    bootstrap_v1_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BootstrapResponse"];
                };
            };
        };
    };
    protocol_document_v1_protocol_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProtocolDocument"];
                };
            };
        };
    };
    delete_session_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_session_v1_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_session_v1_sessions__session_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
